name: notebook
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  - base-notebook=2020.09.05
  # NOTE: pip required for running tests in this repo
  - python=3.7
  - pip=20
  - ipython
  - xarray
  - pytest
  - codecov
  - click
  - pytest-cov
  - climlab
  - numpy
  - scipy
  - sympy
  - numba
  - matplotlib
  - netcdf4
  - pyhdf
  - hdf4
  - h5py
  - attrdict
  - jupytext
  - cartopy
  - pandas
  - pytest
  - conda-lock
# conda-lock -f environment.yml -p linux-64
