{% set version = "0.8.1" %}

package:
  name: climlab
  version: {{ version }}

source:
  path: ../

build:
  skip: True  # [win32 or (win and py27)]
  number: 0

requirements:
  build:
    - python=3.8
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - numpy=1.19
  host:
    - flang  # [win and py3k]
    - python=3.8
    - setuptools
    - pip
    - numpy=1.19
  run:
    - python=3.8
    - numpy=1.19
    - {{ pin_compatible('numpy') }}
    - libflang  # [win and py3k]
    - scipy
    - pydap
    - requests
    - xarray
    - future
    - attrdict

test:
  requires:
    - pytest
    - codecov
    - pytest-cov
  imports:
    - climlab
  commands:
    - pytest -v --pyargs climlab.tests --cov=climlab --cov-config .coveragerc --cov-report term-missing -v
    - codecov

about:
  home: https://github.com/brian-rose/climlab
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package for process-oriented climate modeling
  doc_url: http://climlab.readthedocs.io/
  dev_url: https://github.com/brian-rose/climlab

extra:
  recipe-maintainers:
    - brian-rose
